update (shelli, shello): check for pbcopy + pbpaste

diff --git a/shelli b/shelli
--- a/shelli
+++ b/shelli
@@ -1,5 +1,7 @@
 #! /usr/bin/env bash
 
+[ -n "$(which pbcopy)" ] || echo 'could not find pbcopy'; exit 1
+
 function usage()
 {
   echo "usage ${0##*/} <file_path>"
diff --git a/shello b/shello
--- a/shello
+++ b/shello
@@ -1,5 +1,7 @@
 #! /usr/bin/env bash
 
+[ -n "$(which pbpaste)" ] || echo 'could not find pbpaste'; exit 1
+
 function usage()
 {
   echo "usage ${0##*/} <file_path>"
